#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="iprism_Phase2_QA_28Aug")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertuser_master(user_master instance);
    partial void Updateuser_master(user_master instance);
    partial void Deleteuser_master(user_master instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["iprism_Phase2_QA_28AugConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<user_master> user_masters
		{
			get
			{
				return this.GetTable<user_master>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.USP_AdvanceProjectSearch")]
		public int USP_AdvanceProjectSearch([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> user_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> lid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string project_name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> project_team_member, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string country, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(500)")] string business_unit, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(500)")] string legal_entitity, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string title, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string author, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string identifier, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string project_status, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string project_start_dt_from, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string project_start_dt_to, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string project_end_dt_from, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string project_end_dt_to)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_id, lid, project_name, project_team_member, country, business_unit, legal_entitity, title, author, identifier, project_status, project_start_dt_from, project_start_dt_to, project_end_dt_from, project_end_dt_to);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.USP_GetUserDetailsOnId")]
		public ISingleResult<USP_GetUserDetailsOnIdResult> USP_GetUserDetailsOnId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="Int")] System.Nullable<int> userId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LID", DbType="Int")] System.Nullable<int> lID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userId, lID);
			return ((ISingleResult<USP_GetUserDetailsOnIdResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.user_master")]
	public partial class user_master : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _user_id;
		
		private string _user_name;
		
		private string _first_name;
		
		private string _last_name;
		
		private string _email;
		
		private string _business_unit;
		
		private string _location;
		
		private string _employee;
		
		private System.Nullable<char> _in_house;
		
		private string _platform;
		
		private string _browser;
		
		private string _access_level;
		
		private string _language;
		
		private string _user_password;
		
		private System.Nullable<System.DateTime> _created_date;
		
		private System.Nullable<System.DateTime> _modified_date;
		
		private System.Nullable<int> _created_by;
		
		private System.Nullable<int> _modified_by;
		
		private System.Nullable<int> _status_id;
		
		private System.Nullable<char> _new_password;
		
		private System.Nullable<int> _country_bu_id;
		
		private string _company_name;
		
		private string _country_id;
		
		private string _bu_id;
		
		private System.Nullable<int> _language_id;
		
		private System.Nullable<int> _accesslevel_id;
		
		private string _phone_no;
		
		private string _in_house_contact;
		
		private string _comments;
		
		private string _Training_Code;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(int value);
    partial void Onuser_idChanged();
    partial void Onuser_nameChanging(string value);
    partial void Onuser_nameChanged();
    partial void Onfirst_nameChanging(string value);
    partial void Onfirst_nameChanged();
    partial void Onlast_nameChanging(string value);
    partial void Onlast_nameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onbusiness_unitChanging(string value);
    partial void Onbusiness_unitChanged();
    partial void OnlocationChanging(string value);
    partial void OnlocationChanged();
    partial void OnemployeeChanging(string value);
    partial void OnemployeeChanged();
    partial void Onin_houseChanging(System.Nullable<char> value);
    partial void Onin_houseChanged();
    partial void OnplatformChanging(string value);
    partial void OnplatformChanged();
    partial void OnbrowserChanging(string value);
    partial void OnbrowserChanged();
    partial void Onaccess_levelChanging(string value);
    partial void Onaccess_levelChanged();
    partial void OnlanguageChanging(string value);
    partial void OnlanguageChanged();
    partial void Onuser_passwordChanging(string value);
    partial void Onuser_passwordChanged();
    partial void Oncreated_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oncreated_dateChanged();
    partial void Onmodified_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onmodified_dateChanged();
    partial void Oncreated_byChanging(System.Nullable<int> value);
    partial void Oncreated_byChanged();
    partial void Onmodified_byChanging(System.Nullable<int> value);
    partial void Onmodified_byChanged();
    partial void Onstatus_idChanging(System.Nullable<int> value);
    partial void Onstatus_idChanged();
    partial void Onnew_passwordChanging(System.Nullable<char> value);
    partial void Onnew_passwordChanged();
    partial void Oncountry_bu_idChanging(System.Nullable<int> value);
    partial void Oncountry_bu_idChanged();
    partial void Oncompany_nameChanging(string value);
    partial void Oncompany_nameChanged();
    partial void Oncountry_idChanging(string value);
    partial void Oncountry_idChanged();
    partial void Onbu_idChanging(string value);
    partial void Onbu_idChanged();
    partial void Onlanguage_idChanging(System.Nullable<int> value);
    partial void Onlanguage_idChanged();
    partial void Onaccesslevel_idChanging(System.Nullable<int> value);
    partial void Onaccesslevel_idChanged();
    partial void Onphone_noChanging(string value);
    partial void Onphone_noChanged();
    partial void Onin_house_contactChanging(string value);
    partial void Onin_house_contactChanged();
    partial void OncommentsChanging(string value);
    partial void OncommentsChanged();
    partial void OnTraining_CodeChanging(string value);
    partial void OnTraining_CodeChanged();
    #endregion
		
		public user_master()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="NVarChar(100)")]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this.Onuser_nameChanging(value);
					this.SendPropertyChanging();
					this._user_name = value;
					this.SendPropertyChanged("user_name");
					this.Onuser_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_first_name", DbType="NVarChar(100)")]
		public string first_name
		{
			get
			{
				return this._first_name;
			}
			set
			{
				if ((this._first_name != value))
				{
					this.Onfirst_nameChanging(value);
					this.SendPropertyChanging();
					this._first_name = value;
					this.SendPropertyChanged("first_name");
					this.Onfirst_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_name", DbType="NVarChar(100)")]
		public string last_name
		{
			get
			{
				return this._last_name;
			}
			set
			{
				if ((this._last_name != value))
				{
					this.Onlast_nameChanging(value);
					this.SendPropertyChanging();
					this._last_name = value;
					this.SendPropertyChanged("last_name");
					this.Onlast_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_business_unit", DbType="NVarChar(100)")]
		public string business_unit
		{
			get
			{
				return this._business_unit;
			}
			set
			{
				if ((this._business_unit != value))
				{
					this.Onbusiness_unitChanging(value);
					this.SendPropertyChanging();
					this._business_unit = value;
					this.SendPropertyChanged("business_unit");
					this.Onbusiness_unitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location", DbType="NVarChar(100)")]
		public string location
		{
			get
			{
				return this._location;
			}
			set
			{
				if ((this._location != value))
				{
					this.OnlocationChanging(value);
					this.SendPropertyChanging();
					this._location = value;
					this.SendPropertyChanged("location");
					this.OnlocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employee", DbType="NVarChar(100)")]
		public string employee
		{
			get
			{
				return this._employee;
			}
			set
			{
				if ((this._employee != value))
				{
					this.OnemployeeChanging(value);
					this.SendPropertyChanging();
					this._employee = value;
					this.SendPropertyChanged("employee");
					this.OnemployeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_in_house", DbType="NVarChar(1)")]
		public System.Nullable<char> in_house
		{
			get
			{
				return this._in_house;
			}
			set
			{
				if ((this._in_house != value))
				{
					this.Onin_houseChanging(value);
					this.SendPropertyChanging();
					this._in_house = value;
					this.SendPropertyChanged("in_house");
					this.Onin_houseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_platform", DbType="NVarChar(100)")]
		public string platform
		{
			get
			{
				return this._platform;
			}
			set
			{
				if ((this._platform != value))
				{
					this.OnplatformChanging(value);
					this.SendPropertyChanging();
					this._platform = value;
					this.SendPropertyChanged("platform");
					this.OnplatformChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_browser", DbType="NVarChar(100)")]
		public string browser
		{
			get
			{
				return this._browser;
			}
			set
			{
				if ((this._browser != value))
				{
					this.OnbrowserChanging(value);
					this.SendPropertyChanging();
					this._browser = value;
					this.SendPropertyChanged("browser");
					this.OnbrowserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_access_level", DbType="NVarChar(100)")]
		public string access_level
		{
			get
			{
				return this._access_level;
			}
			set
			{
				if ((this._access_level != value))
				{
					this.Onaccess_levelChanging(value);
					this.SendPropertyChanging();
					this._access_level = value;
					this.SendPropertyChanged("access_level");
					this.Onaccess_levelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_language", DbType="NVarChar(100)")]
		public string language
		{
			get
			{
				return this._language;
			}
			set
			{
				if ((this._language != value))
				{
					this.OnlanguageChanging(value);
					this.SendPropertyChanging();
					this._language = value;
					this.SendPropertyChanged("language");
					this.OnlanguageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_password", DbType="NVarChar(100)")]
		public string user_password
		{
			get
			{
				return this._user_password;
			}
			set
			{
				if ((this._user_password != value))
				{
					this.Onuser_passwordChanging(value);
					this.SendPropertyChanging();
					this._user_password = value;
					this.SendPropertyChanged("user_password");
					this.Onuser_passwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> created_date
		{
			get
			{
				return this._created_date;
			}
			set
			{
				if ((this._created_date != value))
				{
					this.Oncreated_dateChanging(value);
					this.SendPropertyChanging();
					this._created_date = value;
					this.SendPropertyChanged("created_date");
					this.Oncreated_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modified_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> modified_date
		{
			get
			{
				return this._modified_date;
			}
			set
			{
				if ((this._modified_date != value))
				{
					this.Onmodified_dateChanging(value);
					this.SendPropertyChanging();
					this._modified_date = value;
					this.SendPropertyChanged("modified_date");
					this.Onmodified_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_by", DbType="Int")]
		public System.Nullable<int> created_by
		{
			get
			{
				return this._created_by;
			}
			set
			{
				if ((this._created_by != value))
				{
					this.Oncreated_byChanging(value);
					this.SendPropertyChanging();
					this._created_by = value;
					this.SendPropertyChanged("created_by");
					this.Oncreated_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modified_by", DbType="Int")]
		public System.Nullable<int> modified_by
		{
			get
			{
				return this._modified_by;
			}
			set
			{
				if ((this._modified_by != value))
				{
					this.Onmodified_byChanging(value);
					this.SendPropertyChanging();
					this._modified_by = value;
					this.SendPropertyChanged("modified_by");
					this.Onmodified_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status_id", DbType="Int")]
		public System.Nullable<int> status_id
		{
			get
			{
				return this._status_id;
			}
			set
			{
				if ((this._status_id != value))
				{
					this.Onstatus_idChanging(value);
					this.SendPropertyChanging();
					this._status_id = value;
					this.SendPropertyChanged("status_id");
					this.Onstatus_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_new_password", DbType="NVarChar(1)")]
		public System.Nullable<char> new_password
		{
			get
			{
				return this._new_password;
			}
			set
			{
				if ((this._new_password != value))
				{
					this.Onnew_passwordChanging(value);
					this.SendPropertyChanging();
					this._new_password = value;
					this.SendPropertyChanged("new_password");
					this.Onnew_passwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country_bu_id", DbType="Int")]
		public System.Nullable<int> country_bu_id
		{
			get
			{
				return this._country_bu_id;
			}
			set
			{
				if ((this._country_bu_id != value))
				{
					this.Oncountry_bu_idChanging(value);
					this.SendPropertyChanging();
					this._country_bu_id = value;
					this.SendPropertyChanged("country_bu_id");
					this.Oncountry_bu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_company_name", DbType="NVarChar(100)")]
		public string company_name
		{
			get
			{
				return this._company_name;
			}
			set
			{
				if ((this._company_name != value))
				{
					this.Oncompany_nameChanging(value);
					this.SendPropertyChanging();
					this._company_name = value;
					this.SendPropertyChanged("company_name");
					this.Oncompany_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country_id", DbType="NVarChar(50)")]
		public string country_id
		{
			get
			{
				return this._country_id;
			}
			set
			{
				if ((this._country_id != value))
				{
					this.Oncountry_idChanging(value);
					this.SendPropertyChanging();
					this._country_id = value;
					this.SendPropertyChanged("country_id");
					this.Oncountry_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bu_id", DbType="NVarChar(500)")]
		public string bu_id
		{
			get
			{
				return this._bu_id;
			}
			set
			{
				if ((this._bu_id != value))
				{
					this.Onbu_idChanging(value);
					this.SendPropertyChanging();
					this._bu_id = value;
					this.SendPropertyChanged("bu_id");
					this.Onbu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_language_id", DbType="Int")]
		public System.Nullable<int> language_id
		{
			get
			{
				return this._language_id;
			}
			set
			{
				if ((this._language_id != value))
				{
					this.Onlanguage_idChanging(value);
					this.SendPropertyChanging();
					this._language_id = value;
					this.SendPropertyChanged("language_id");
					this.Onlanguage_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_accesslevel_id", DbType="Int")]
		public System.Nullable<int> accesslevel_id
		{
			get
			{
				return this._accesslevel_id;
			}
			set
			{
				if ((this._accesslevel_id != value))
				{
					this.Onaccesslevel_idChanging(value);
					this.SendPropertyChanging();
					this._accesslevel_id = value;
					this.SendPropertyChanged("accesslevel_id");
					this.Onaccesslevel_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone_no", DbType="NVarChar(50)")]
		public string phone_no
		{
			get
			{
				return this._phone_no;
			}
			set
			{
				if ((this._phone_no != value))
				{
					this.Onphone_noChanging(value);
					this.SendPropertyChanging();
					this._phone_no = value;
					this.SendPropertyChanged("phone_no");
					this.Onphone_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_in_house_contact", DbType="NVarChar(100)")]
		public string in_house_contact
		{
			get
			{
				return this._in_house_contact;
			}
			set
			{
				if ((this._in_house_contact != value))
				{
					this.Onin_house_contactChanging(value);
					this.SendPropertyChanging();
					this._in_house_contact = value;
					this.SendPropertyChanged("in_house_contact");
					this.Onin_house_contactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comments", DbType="NVarChar(250)")]
		public string comments
		{
			get
			{
				return this._comments;
			}
			set
			{
				if ((this._comments != value))
				{
					this.OncommentsChanging(value);
					this.SendPropertyChanging();
					this._comments = value;
					this.SendPropertyChanged("comments");
					this.OncommentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Training_Code", DbType="NVarChar(250)")]
		public string Training_Code
		{
			get
			{
				return this._Training_Code;
			}
			set
			{
				if ((this._Training_Code != value))
				{
					this.OnTraining_CodeChanging(value);
					this.SendPropertyChanging();
					this._Training_Code = value;
					this.SendPropertyChanged("Training_Code");
					this.OnTraining_CodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class USP_GetUserDetailsOnIdResult
	{
		
		private int _user_id;
		
		private string _User_name;
		
		private string _first_name;
		
		private string _last_name;
		
		private string _email;
		
		private string _business_unit;
		
		private string _location;
		
		private string _employee;
		
		private System.Nullable<char> _in_house;
		
		private string _access_level;
		
		private string _company_name;
		
		private System.Nullable<int> _status_id;
		
		private string _country_id;
		
		private string _bu_id;
		
		private System.Nullable<int> _language_id;
		
		private System.Nullable<int> _accesslevel_id;
		
		private string _phone_no;
		
		private string _in_house_contact;
		
		private string _comments;
		
		private System.Nullable<System.DateTime> _created_date;
		
		private System.Nullable<int> _created_by;
		
		private System.DateTime _modifieddate;
		
		private System.Nullable<int> _modified_by;
		
		private string _modified_Name;
		
		private string _created_name;
		
		public USP_GetUserDetailsOnIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int NOT NULL")]
		public int user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this._user_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_name", DbType="NVarChar(100)")]
		public string User_name
		{
			get
			{
				return this._User_name;
			}
			set
			{
				if ((this._User_name != value))
				{
					this._User_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_first_name", DbType="NVarChar(100)")]
		public string first_name
		{
			get
			{
				return this._first_name;
			}
			set
			{
				if ((this._first_name != value))
				{
					this._first_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_name", DbType="NVarChar(100)")]
		public string last_name
		{
			get
			{
				return this._last_name;
			}
			set
			{
				if ((this._last_name != value))
				{
					this._last_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_business_unit", DbType="NVarChar(100)")]
		public string business_unit
		{
			get
			{
				return this._business_unit;
			}
			set
			{
				if ((this._business_unit != value))
				{
					this._business_unit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location", DbType="NVarChar(100)")]
		public string location
		{
			get
			{
				return this._location;
			}
			set
			{
				if ((this._location != value))
				{
					this._location = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employee", DbType="NVarChar(100)")]
		public string employee
		{
			get
			{
				return this._employee;
			}
			set
			{
				if ((this._employee != value))
				{
					this._employee = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_in_house", DbType="NVarChar(1)")]
		public System.Nullable<char> in_house
		{
			get
			{
				return this._in_house;
			}
			set
			{
				if ((this._in_house != value))
				{
					this._in_house = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_access_level", DbType="NVarChar(100)")]
		public string access_level
		{
			get
			{
				return this._access_level;
			}
			set
			{
				if ((this._access_level != value))
				{
					this._access_level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_company_name", DbType="NVarChar(100)")]
		public string company_name
		{
			get
			{
				return this._company_name;
			}
			set
			{
				if ((this._company_name != value))
				{
					this._company_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status_id", DbType="Int")]
		public System.Nullable<int> status_id
		{
			get
			{
				return this._status_id;
			}
			set
			{
				if ((this._status_id != value))
				{
					this._status_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country_id", DbType="NVarChar(50)")]
		public string country_id
		{
			get
			{
				return this._country_id;
			}
			set
			{
				if ((this._country_id != value))
				{
					this._country_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bu_id", DbType="NVarChar(500)")]
		public string bu_id
		{
			get
			{
				return this._bu_id;
			}
			set
			{
				if ((this._bu_id != value))
				{
					this._bu_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_language_id", DbType="Int")]
		public System.Nullable<int> language_id
		{
			get
			{
				return this._language_id;
			}
			set
			{
				if ((this._language_id != value))
				{
					this._language_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_accesslevel_id", DbType="Int")]
		public System.Nullable<int> accesslevel_id
		{
			get
			{
				return this._accesslevel_id;
			}
			set
			{
				if ((this._accesslevel_id != value))
				{
					this._accesslevel_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone_no", DbType="NVarChar(50)")]
		public string phone_no
		{
			get
			{
				return this._phone_no;
			}
			set
			{
				if ((this._phone_no != value))
				{
					this._phone_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_in_house_contact", DbType="NVarChar(100)")]
		public string in_house_contact
		{
			get
			{
				return this._in_house_contact;
			}
			set
			{
				if ((this._in_house_contact != value))
				{
					this._in_house_contact = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comments", DbType="NVarChar(250)")]
		public string comments
		{
			get
			{
				return this._comments;
			}
			set
			{
				if ((this._comments != value))
				{
					this._comments = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> created_date
		{
			get
			{
				return this._created_date;
			}
			set
			{
				if ((this._created_date != value))
				{
					this._created_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_by", DbType="Int")]
		public System.Nullable<int> created_by
		{
			get
			{
				return this._created_by;
			}
			set
			{
				if ((this._created_by != value))
				{
					this._created_by = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modifieddate", DbType="DateTime NOT NULL")]
		public System.DateTime modifieddate
		{
			get
			{
				return this._modifieddate;
			}
			set
			{
				if ((this._modifieddate != value))
				{
					this._modifieddate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modified_by", DbType="Int")]
		public System.Nullable<int> modified_by
		{
			get
			{
				return this._modified_by;
			}
			set
			{
				if ((this._modified_by != value))
				{
					this._modified_by = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modified_Name", DbType="NVarChar(100)")]
		public string modified_Name
		{
			get
			{
				return this._modified_Name;
			}
			set
			{
				if ((this._modified_Name != value))
				{
					this._modified_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_name", DbType="NVarChar(100)")]
		public string created_name
		{
			get
			{
				return this._created_name;
			}
			set
			{
				if ((this._created_name != value))
				{
					this._created_name = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
